version: '3.8'

services:
   db:
     image: mysql:5.7
     volumes:
       - dbdata:/var/lib/mysql
     restart: always
     ports:
       - "3306:3306"
     environment:
       MYSQL_DATABASE: mysql
       MYSQL_ROOT_PASSWORD: my-secret123
       MYSQL_USER: user123
       MYSQL_PASSWORD: my-secret123

volumes:
    dbdata:
